version: '3'

services:
  exercise_score_predictor:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: exercise_scoring
    ports:
      - "5000:5000"
    restart: on-failure